title: "The Family Hilton Blog Site"
url: "https://stephen-hilton.github.io"
baseurl: "/familyhilton.com" # or "/repo-name"
remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-seo-tag